# Netflix Movies and TV Shows Analysis

## Dataset Info:
This dataset contains information about movies and TV shows available on Netflix, including title, genre, release year, duration, and ratings.

**Dataset Source:** [Netflix Movies and TV Shows on Kaggle](https://www.kaggle.com/datasets/shivamb/netflix-shows)

https://drive.google.com/file/d/1zcQ9XXnzH34B8FNZR11vMThVNwEd6E0I/view?usp=sharing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load necessary libraries
import numpy as np
import pandas as pd

In [ ]:
# Load the dataset

# read_csv, read_excel
path = '/content/drive/MyDrive/netflix_titles.csv'
df = pd.read_csv(path)

In [ ]:
# shape of the dataframe
df.shape

(8807, 12)

## Data Exploration

### 1. Display the first 5 rows of the dataset

In [ ]:
# Code here
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### 2. How many total movies and TV shows are available on Netflix?

In [ ]:
# Code here
df.type.value_counts().reset_index().style.background_gradient()

### 3. List the unique genres available in the dataset.

In [ ]:
df.shape

(8807, 12)

In [ ]:
df['listed_in'][50]

'International TV Shows, TV Dramas, TV Sci-Fi & Fantasy'

In [ ]:
df['listed_in'][50].split(",")

['International TV Shows', ' TV Dramas', ' TV Sci-Fi & Fantasy']

In [ ]:
d = {}
for genre in df['listed_in'][50].split(","):
  if genre in d.keys():

International TV Shows
 TV Dramas
 TV Sci-Fi & Fantasy

In [ ]:
s = set()
for i in range(len(df)):
  all_genres_list = df['listed_in'][i].split(",")
  # print(all_genres_list)
  for genre in all_genres_list:
    s.add(genre.strip())

len(s)

42

In [ ]:
s

{'Action & Adventure',
 'Anime Features',
 'Anime Series',
 'British TV Shows',
 'Children & Family Movies',
 'Classic & Cult TV',
 'Classic Movies',
 'Comedies',
 'Crime TV Shows',
 'Cult Movies',
 'Documentaries',
 'Docuseries',
 'Dramas',
 'Faith & Spirituality',
 'Horror Movies',
 'Independent Movies',
 'International Movies',
 'International TV Shows',
 "Kids' TV",
 'Korean TV Shows',
 'LGBTQ Movies',
 'Movies',
 'Music & Musicals',
 'Reality TV',
 'Romantic Movies',
 'Romantic TV Shows',
 'Sci-Fi & Fantasy',
 'Science & Nature TV',
 'Spanish-Language TV Shows',
 'Sports Movies',
 'Stand-Up Comedy',
 'Stand-Up Comedy & Talk Shows',
 'TV Action & Adventure',
 'TV Comedies',
 'TV Dramas',
 'TV Horror',
 'TV Mysteries',
 'TV Sci-Fi & Fantasy',
 'TV Shows',
 'TV Thrillers',
 'Teen TV Shows',
 'Thrillers'}

In [ ]:
# Code here
# listed_in / genre
genres_dict = {}

for i in range(len(df)):
  all_genres_list = df['listed_in'][i].split(",")
  for genre in all_genres_list:
    genre = genre.strip()
    if genre in genres_dict.keys():
      genres_dict[genre] += 1
    else:
      genres_dict[genre] = 1

genres_dict

{'Documentaries': 869,
 'International TV Shows': 1351,
 'TV Dramas': 763,
 'TV Mysteries': 98,
 'Crime TV Shows': 470,
 'TV Action & Adventure': 168,
 'Docuseries': 395,
 'Reality TV': 255,
 'Romantic TV Shows': 370,
 'TV Comedies': 581,
 'TV Horror': 75,
 'Children & Family Movies': 641,
 'Dramas': 2427,
 'Independent Movies': 756,
 'International Movies': 2752,
 'British TV Shows': 253,
 'Comedies': 1674,
 'Spanish-Language TV Shows': 174,
 'Thrillers': 577,
 'Romantic Movies': 616,
 'Music & Musicals': 375,
 'Horror Movies': 357,
 'Sci-Fi & Fantasy': 243,
 'TV Thrillers': 57,
 "Kids' TV": 451,
 'Action & Adventure': 859,
 'TV Sci-Fi & Fantasy': 84,
 'Classic Movies': 116,
 'Anime Features': 71,
 'Sports Movies': 219,
 'Anime Series': 176,
 'Korean TV Shows': 151,
 'Science & Nature TV': 92,
 'Teen TV Shows': 69,
 'Cult Movies': 71,
 'TV Shows': 16,
 'Faith & Spirituality': 65,
 'LGBTQ Movies': 102,
 'Stand-Up Comedy': 343,
 'Movies': 57,
 'Stand-Up Comedy & Talk Shows': 56,
 'Classic & Cult TV': 28}

## Data Cleaning

### 4. Check for missing values. Which columns have missing data?

In [ ]:
# Code here
100 * df.isna().sum() / len(df)

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [ ]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df[df['duration'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

### 5. Fill missing director names with 'Unknown'.

In [ ]:
# Code here
df['director'] = df['director'].fillna("Unknown")

In [ ]:
df.director.value_counts()

director
Unknown                                   2634
Rajiv Chilaka                               19
Raúl Campos, Jan Suter                      18
Suhas Kadav                                 16
Marcus Raboy                                16
                                          ...
Milla Harrison-Hansley, Alicky Sussman       1
Drew Stone                                   1
Benjamin Turner                              1
S. Shankar                                   1
Peter Hewitt                                 1
Name: count, Length: 4529, dtype: int64

## Data Analysis & Aggregation

### 6. What is the distribution of content type (Movies vs. TV Shows)?

In [ ]:
# Code here
df.type.value_counts().reset_index().style.background_gradient()

### 7. Find the top 5 years with the most content added.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df1 = df.dropna(subset = ['date_added'])
df1.shape

(8797, 12)

In [ ]:
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])
df['date_added'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8807 entries, 0 to 8806
Series name: date_added
Non-Null Count  Dtype
--------------  -----
8797 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 68.9 KB

In [ ]:
# Code here
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [ ]:
df['added_year'] = df['date_added'].dt.year

df['added_year'].value_counts().reset_index().head(5)

   added_year  count
0      2019.0   2016
1      2020.0   1879
2      2018.0   1649
3      2021.0   1498
4      2017.0   1188

### 8. Find the number of movies released before 2000.

In [ ]:
# Code here
df.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,added_year
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0

In [ ]:
df[df['release_year'] < 2000].shape

(525, 13)

### 9. Drop any duplicate rows from the dataset.

In [ ]:
# Code here
 df.drop_duplicates()

### 10. Convert the "date_added" column to datetime format.

In [ ]:
df['date_added'] = pd.to_datetime(df['date_added'])

### 11. Extract the year from the "date_added" column and create a new column called "added_year".

In [ ]:
df['added_year'] = df['date_added'].dt.year

### 12.Fill missing values in the "rating" column with "Not Rated".

In [ ]:
df['rating'].isna().sum()

np.int64(4)

In [ ]:
df['rating'] = df['rating'].fillna("Not Rated")

### 13. Find the top 5 years with the most content added.

In [ ]:
df['added_year'].value_counts().reset_index().head(5).style.background_gradient()

### 14. Find the number of movies released before the year 2000.

In [ ]:
# Filter for movies released before 2000
movies_before_2000 = df[(df['type'] == 'Movie') & (df['release_year'] < 2000)]

# Count them
count_movies_before_2000 = movies_before_2000.shape[0]

count_movies_before_2000

### 15. Identify the top 10 actors who have appeared the most in Netflix content.

In [ ]:
# df.country.value_counts()

In [ ]:
# Code here
df.sample(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,added_year
6948,s6949,Movie,Heal,Kelly Noonan,"Kelly Noonan, Deepak Chopra, Michael Beckwith,...",United States,2019-02-01,2017,TV-14,107 min,Documentaries,"Stories from spiritual leaders, physicians and...",2019.0
971,s972,Movie,Between Worlds,Maria Pulera,"Nicolas Cage, Franka Potente, Penelope Mitchel...",Spain,2021-04-27,2018,R,91 min,Thrillers,"Grieving for his dead wife and daughter, a tru...",2021.0

### 16. What is the average duration of movies in minutes?

In [ ]:
# Code here
movie_df = df[df['type'] == 'Movie']
movie_df.shape

(6131, 13)

In [ ]:
movie_df.reset_index()

In [ ]:
movie_df.reset_index(drop = True, inplace = True)

In [ ]:
movie_df['duration'][0]

'90 min'

In [ ]:
int('90 min'.split()[0])

90

In [ ]:
def extract_numeric(s):
  return int(s.split()[0])

extract_numeric('90 min')

90

In [ ]:
movie_df1 = movie_df.dropna(subset = ['duration'])

In [ ]:
movie_df1['duration_numeric'] = movie_df1['duration'].apply(extract_numeric)
# movie_df['duration_numeric'] = movie_df['duration'].apply(lambda x: int(x.split()[0]))
movie_df1['duration_numeric']

/tmp/ipython-input-2467886775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_df1['duration_numeric'] = movie_df1['duration'].apply(extract_numeric)

0        90
1        91
2       125
3       104
4       127
       ...
6126     96
6127    158
6128     88
6129     88
6130    111
Name: duration_numeric, Length: 6128, dtype: int64

In [ ]:
movie_df1['duration_numeric'].mean()

np.float64(99.57718668407311)

In [ ]:
# release_year wise average duration
movie_df1.groupby('release_year').agg({'duration_numeric':['min', 'max', 'mean'], 'show_id':'nunique'}).reset_index()

   release_year duration_numeric                 show_id
                             min  max       mean nunique
0          1942               18   52  35.000000       2
1          1943               45   82  62.666667       3
2          1944               40   76  52.000000       3
3          1945               32   63  51.333333       3
4          1946               58   58  58.000000       1
..          ...              ...  ...        ...     ...
68         2017               11  212  95.535248     766
69         2018               12  312  96.185137     767
70         2019               10  209  93.466035     633
71         2020                5  190  92.141199     517
72         2021               13  273  96.444043     277

[73 rows x 5 columns]

### 17. Find the most common genre on Netflix.

In [ ]:
# Code here

### 18. Find the shortest and longest movies available on Netflix.

In [ ]:
movie_df1['duration_numeric'].describe().T

count    6128.000000
mean       99.577187
std        28.290593
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration_numeric, dtype: float64

In [ ]:
display(movie_df1.nlargest(2, 'duration_numeric'))

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,added_year,duration_numeric
2703,s4254,Movie,Black Mirror: Bandersnatch,Unknown,"Fionn Whitehead, Will Poulter, Craig Parkinson...",United States,2018-12-28,2018,TV-MA,312 min,"Dramas, International Movies, Sci-Fi & Fantasy","In 1984, a young programmer begins to question...",2018.0,312
449,s718,Movie,Headspace: Unwind Your Mind,Unknown,"Andy Puddicombe, Evelyn Lewis Prieto, Ginger D...",NaN,2021-06-15,2021,TV-G,273 min,Documentaries,"Do you want to relax, meditate or sleep deeply...",2021.0,273

In [ ]:
movie_df1.nsmallest(2, 'duration_numeric')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,added_year,duration_numeric
2402,s3778,Movie,Silent,"Limbert Fabian, Brandon Oldenburg",NaN,United States,2019-06-04,2014,TV-Y,3 min,"Children & Family Movies, Sci-Fi & Fantasy","""Silent"" is an animated short film created by ...",2019.0,3
1777,s2714,Movie,Sol Levante,Akira Saitoh,NaN,Japan,2020-04-02,2020,TV-14,5 min,"Action & Adventure, Anime Features, Internatio...",A young warrior and her familiar search for th...,2020.0,5

### 19. Count the number of TV shows that have more than 5 seasons.

In [ ]:
tv_show_df = df[df['type'] == 'TV Show']
tv_show_df.shape

(2676, 13)

In [ ]:
tv_show_df['duration']

1       2 Seasons
2        1 Season
3        1 Season
4       2 Seasons
5        1 Season
          ...
8795    2 Seasons
8796    2 Seasons
8797    3 Seasons
8800     1 Season
8803    2 Seasons
Name: duration, Length: 2676, dtype: object

In [ ]:
tv_show_df['duration_numeric'] = tv_show_df['duration'].apply(lambda x: int(x.split()[0]))
tv_show_df['duration_numeric']

/tmp/ipython-input-379469215.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tv_show_df['duration_numeric'] = tv_show_df['duration'].apply(lambda x: int(x.split()[0]))

1       2
2       1
3       1
4       2
5       1
       ..
8795    2
8796    2
8797    3
8800    1
8803    2
Name: duration_numeric, Length: 2676, dtype: int64

In [ ]:
tv_show_df[tv_show_df['duration_numeric'] > 5].shape

(99, 14)

### 20. What is the most frequent rating given to Netflix content?

In [ ]:
df.rating.value_counts()

rating
TV-MA        3207
TV-14        2160
TV-PG         863
R             799
PG-13         490
TV-Y7         334
TV-Y          307
PG            287
TV-G          220
NR             80
G              41
TV-Y7-FV        6
Not Rated       4
NC-17           3
UR              3
66 min          1
74 min          1
84 min          1
Name: count, dtype: int64

### 21. Find the most common country of production for Netflix content.

In [ ]:
df.country.value_counts()

country
United States                                                      2818
India                                                               972
United Kingdom                                                      419
Japan                                                               245
South Korea                                                         199
                                                                   ...
Mexico, United States, Spain, Colombia                                1
Canada, Norway                                                        1
Finland, Germany, Belgium                                             1
Argentina, United States, Mexico                                      1
United Kingdom, United States, Germany, Denmark, Belgium, Japan       1
Name: count, Length: 748, dtype: int64